### ISSUE TITLE
terraform plan fails when resources deleted in Clumio but not terraform state

### ISSUE THREAD

**Issue by BenMcClainCarpe** [clumio-code/terraform-provider-clumio#57]
I recently did a major refactor of the Terraform supporting my Clumio infrastructure.  As such, I did some of the work of cleaning up things in the Clumio UI so I could have a better visual of what I was doing.  This included deleting S3 protection groups, removing buckets from others, and deleting backup policies.  
I ran a `terraform plan` after getting my terraform to where I wanted it to be to see if I did anything wrong in Terraform.  I had expected it to complain, ask to delete things that weren't there, or otherwise give me some understandable errors.  However I got the below and thought you should know.  After doing a `terraform state rm` on those items I removed in the UI the error no longer happens.  I'm not blocked by this, but I thought you'd want to know.  
I removed these resources:  
* `clumio_policy`
* `clumio_policy_assignment`
* `clumio_protection_group`

```
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).ValidateResourceConfig request was cancelled.
╵
╷
│ Error: Error retrieving Clumio Policy.
│
│ Error: {"errors":[{"error_code":22,"error_message":"An invalid Policy ID parameter was provided: '90d6e179-5c46-49db-881c-a8a59ff95091'."}]}
│
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).ValidateDataResourceConfig request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).ValidateResourceConfig request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).ValidateDataResourceConfig request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ValidateResourceConfig call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).ValidateResourceConfig request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ValidateDataResourceConfig call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).ValidateDataResourceConfig request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).ValidateResourceConfig request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

Stack trace from the terraform-provider-clumio_v0.5.8 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x104fbedfc]

goroutine 72 [running]:
github.com/clumio-code/terraform-provider-clumio/clumio/plugin_framework/clumio_policy_assignment.(*clumioPolicyAssignmentResource).Read(0x14000398000, {0x10550d678, 0x140007be0c0}, {{{{0x105511cc0, 0x140007bedb0}, {0x105413600, 0x140007bec90}}, {0x105513570, 0x1400042d270}}, 0x14000398078, ...}, ...)
	github.com/clumio-code/terraform-provider-clumio/clumio/plugin_framework/clumio_policy_assignment/resource_policy_assignment.go:237 +0x3cc
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0x14000189a20, {0x10550d678, 0x140007be0c0}, 0x140007be150, 0x140005df5c0)
	github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/fwserver/server_readresource.go:101 +0x508
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0x14000189a20, {0x10550d678?, 0x1400016c0c0?}, 0x14000208c00)
	github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/proto6server/server_readresource.go:55 +0x314
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0x140001d4780, {0x10550d678?, 0x14000165920?}, 0x14000098d80)
	github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/tf6server/server.go:787 +0x3e8
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x1054d8480?, 0x140001d4780}, {0x10550d678, 0x14000165920}, 0x140003d0400, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:431 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140001d21e0, {0x10550d678, 0x14000251dd0}, {0x105511ff8, 0x140004024e0}, 0x1400031d200, 0x140003244b0, 0x1059b44e8, 0x0)
	google.golang.org/grpc@v1.59.0/server.go:1343 +0xc6c
google.golang.org/grpc.(*Server).handleStream(0x140001d21e0, {0x105511ff8, 0x140004024e0}, 0x1400031d200)
	google.golang.org/grpc@v1.59.0/server.go:1737 +0x9f0
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.59.0/server.go:986 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.59.0/server.go:997 +0x174

Error: The terraform-provider-clumio_v0.5.8 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by prakkarp** [comment]
Thanks for raising this issue. I will address this as part of the next release.
